#!/bin/bash

if [ $# -ne 8 ];
then
echo usage: $0 '[region] [window] [ref] [truth] [targets] [bam] [vcf] [output]'
echo generates hhga data for this region in the current directory
exit
fi

region=$1
window_size=$2
ref=$3
ground_truth=$4
ground_callable=$5
input_bam=$6
vcf=$7
output_dir=$8

mkdir -p $output_dir

variant_calls=$vcf

ground_region=$output_dir/$region.ground_truth.vcf.gz
normalized_variants=$output_dir/$region.norm.vcf.gz
callable_variants=$output_dir/$region.callable.vcf.gz
uncallable_variants=$output_dir/$region.uncallable.vcf.gz
passing_variants=$output_dir/$region.pass.vcf.gz
labeled_variants=$output_dir/$region.label.vcf.gz
hhga_genotypes=$output_dir/$region.hhga.gz

tabix -h $ground_truth $region \
    | vcfintersect -b <(zcat $ground_callable) \
    | vcfallelicprimitives \
    | vt normalize -r $ref -q - 2>/dev/null \
    | vcffixup - \
    | vcffilter -f 'AC > 0' \
    | vcfunphase - \
    | vcfnull2ref - \
    | bgziptabix $ground_region

tabix -h $variant_calls $region \
    | vcfallelicprimitives -kg \
    | vt normalize -r $ref -q - 2>/dev/null \
    | vcfunphase - \
    | vcfnull2ref - \
    | vcfstreamsort -w 100000 | bgziptabix $normalized_variants

vcfintersect -b <(zcat $ground_callable) $normalized_variants | bgziptabix $callable_variants
vcfintersect -v -b <(zcat $ground_callable) $normalized_variants | bgziptabix $uncallable_variants

#zcat $callable_variants \
#    | vcfannotategenotypes groundGT - $ground_region \
#    | vcfunphase - \
#    | vcfnull2ref - \
#    | bgziptabix $labeled_variants

zcat $callable_variants \
    | vcfannotategenotypes GT - $ground_region \
    | vcfunphase - \
    | vcfnull2ref - \
    | bgziptabix $passing_variants

hhga -f $ref -r $region -b $input_bam -v $passing_variants -w $window_size -g \
    | gzip >$hhga_genotypes

rm -f $ground_region*
rm -f $normalized_variants*
rm -f $callable_variants*
rm -f $uncallable_variants*
rm -f $passing_variants*

